config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'

  resources :events do
    get :publish
    get :republish
  end

  resources :parties
end

app/models/event.rb
class Event < ApplicationRecord
  ACTIVITIES = ["Defensa 50v50", "Ataque 50v50", "PvP openworld"]
  EVENT_BANNER = {
    "Windsward" => "https://i.imgur.com/YGHvxxi.png",
    "Brightwood" => "https://i.imgur.com/FeJnfDo.png",
    "Coutlass Keys" => "https://i.imgur.com/8jQ9BsE.png",
    "Ebonscale" => "https://i.imgur.com/JpMz9ND.png",
    "Everfall" => "https://i.imgur.com/2bcVuo1.png",
    "First Light" => "https://i.imgur.com/IYnHk49.png",
    "Monarchs Bluffs" => "https://i.imgur.com/srr9ZQA.png",
    "Mourningdale" => "https://i.imgur.com/GRw5hyO.png",
    "Restless Shore" => "https://i.imgur.com/9x6No8m.png",
    "Weavers Fen" => "https://i.imgur.com/pxDq6hB.png"
  }

  has_many :event_attendees
  has_one :event_party

  def edit_msg
    url = "https://www.lokthar.com/logo-clear.png"

    fields_hash = event_party.parties_hash.select{|party| party[:name] != "Party 4"}
    party_4     = event_party.parties_hash.select{|party| party[:name] == "Party 4"}.first[:value].split("\n").join(" - ")

    embed_hash = {
      :title=>name,
      :description=>"#{EmojiWritter.new(name).process} \n\n#{event_details}\n\n Editado de nuevo el : #{Time.now}. __Squad__: #{event_party.title}\n\n**Party 4** #{party_4 || "Armas de asedio"}",
      :url=>nil,
      :timestamp=>"2021-11-28T20:05:20Z",
      :color=>0x8700f5,
      :footer=>{
        :icon_url => "https://i.imgur.com/61tyXNu.png",
        :text => "Si tienen algun problema con el bot, PM a Ksix"
      },
      :image=>{ :url => Event::EVENT_BANNER[location] },
      :thumbnail=>nil,
      :video=>nil,
      :provider=>nil,
      :author=>nil,
      :fields=> fields_hash
    }

    discord_messages.each do |msg_log|
      message = DiscordBot.bot.channel(msg_log["channel"]).message(msg_log["message"])
      message.edit("@everyone", embed_hash) if message
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy, :publish, :republish]

  def index
    @events = Event.where(listed: true).order(created_at: :desc)
  end

  def show; end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to events_path
    else
      render :edit
    end
  end

  def destroy
    @event.update(listed: false)
    redirect_to events_path
  end

  def publish
    @event.update(published_at: Time.now)
    DiscordMessenger::EventBasic.new(event: @event, setup: params[:setup_id]).deliver

    redirect_to @event
  end

  def republish
    DiscordMessenger::EventBasic.new(event: @event).republish
    redirect_to @event
  end

  protected

  def set_event
    @event = Event.find(params[:id] || params[:event_id])
  end

  def event_params
    params.require(:event).permit(:activity, :name, :starts_at,
      :location, :tanks_needed, :healers_needed, :melee_dps_needed,
      :ranged_dps_needed, :mages_needed, :event_details, :event_image_url
    )
  end

end

app/views/events/_form.erb
<%= form_with model: @event, class: "p-4 shadow-md rounded-md text-left text-white max-w-sm" do |f| %>
    <%= f.label :name do %>
      <span class="text-gray-400 block">Nombre del evento</span>
      <%= f.text_field :name, placeholder: "War 50v50 en ...", class: "form-input mt-1 block w-full text-gray-700" %>
    <% end %>

    <%= f.label :event_details do %>
      <span class="text-gray-400 block">Detalles del evento</span>
      <%= f.text_field :event_details, placeholder: "Arrancamos a juntarnos en discord 30 minutos antes...", class: "form-input mt-1 block w-full text-gray-700" %>
    <% end %>

    <div class="mt-4">
      <%= f.label :location, "Lugar del evento", class: "text-gray-400 block" %>
      <%= f.select :location, Event::EVENT_BANNER.keys, {}, {class: "form-select mt-1 block w-full text-gray-700"} %>
    </div>

    <div class="mt-4">
      <%= f.label :activity, "Tipo de evento", class: "text-gray-400 block" %>
      <%= f.select :activity, Event::ACTIVITIES, {}, {class: "form-select mt-1 block w-full text-gray-700"} %>  
    </div>

    <div class="mt-4">
      <%= f.label :starts_at, "Fecha", class: "text-gray-400 block" %>
      <%= f.datetime_field :starts_at, min: Date.today, class: 'form-input text-gray-700 mt-1' %>
    </div>

    <div class="mt-4">
      <%= f.label :healers_needed, "Cantidad necesaria de Healers (opcional)", class: 'text-gray-400 block' %>
      <%= f.number_field :healers_needed, min: 0, class: 'form-input text-gray-700 mt-1 w-full'%>
    </div>

    <div class="mt-4">
      <%= f.label :tanks_needed, "Cantidad necesaria de Tanks (opcional)", class: 'text-gray-400 block' %>
      <%= f.number_field :tanks_needed, min: 0, class: 'form-input text-gray-700 mt-1 w-full'%>
    </div>

    <div class="mt-4">
      <%= f.label :melee_dps_needed, "Cantidad necesaria de Melee DPS (opcional)", class: 'text-gray-400 block' %>
      <%= f.number_field :melee_dps_needed, min: 0, class: 'form-input text-gray-700 mt-1 w-full'%>
    </div>

    <div class="mt-4">
      <%= f.label :mages_needed, "Cantidad necesaria de Magos (opcional)", class: 'text-gray-400 block' %>
      <%= f.number_field :mages_needed, min: 0, class: 'form-input text-gray-700 mt-1 w-full'%>
    </div>

    <div class="mt-4">
      <%= f.label :ranged_dps_needed, "Cantidad necesaria de DPS Rango (opcional)", class: 'text-gray-400 block' %>
      <%= f.number_field :ranged_dps_needed, min: 0, class: 'form-input text-gray-700 mt-1 w-full'%>
    </div>

    <div class="mt-4">
      <%= f.submit 'Guardar', class: 'bg-purple-500 text-white active:bg-purple-600 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150' %>
    </div>
  <% end %>

app/views/events/edit.html.erb
<!-- Required form plugin -->
<link
  href="https://cdn.jsdelivr.net/npm/@tailwindcss/custom-forms@0.2.1/dist/custom-forms.css"
  rel="stylesheet"
/>
<section class="px-4 md:px-10 overflow-auto custom-scrollbar text-white" style="z-index: 999;">
  <%= render 'form' %>
</section>

app/views/events/index.html.erb
<section class="px-4 md:px-10 overflow-auto custom-scrollbar text-white" style="z-index: 999;">

<a class="text-purple-500 bg-transparent border border-solid border-purple-500 hover:bg-purple-500 hover:text-white active:bg-purple-600 font-bold uppercase text-sm px-6 py-3 rounded mr-1 mb-1 ease-linear transition-all duration-150" type="button" href="/events/new">
  Crear nuevo evento
</a>
<div class="flex flex-col w-full mt-4">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-900 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-900">
          <thead class="bg-gray-800">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Event
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Description
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Status
              </th>
              <th scope="col" class="relative px-6 py-3">
                <span class="sr-only">Edit</span>
              </th>
            </tr>
          </thead>
          <tbody class="bg-gray-700 divide-y divide-gray-900">
            <% @events.each do |event| %>
              <tr>
                <td class="px-6 py-4 whitespace-nowrap">
                  <%= link_to event_path(event) do %>
                    <div class="flex items-center">
                      <div class="flex-shrink-0 h-10 w-10">
                        <img class="h-10 w-10 rounded-full" src="https://i.imgur.com/Tm1HTIA.png" alt="">
                      </div>
                      <div class="ml-4">
                        <div class="text-sm font-medium text-gray-100">
                          <%= event.name %>
                        </div>
                        <div class="text-sm text-gray-400">
                          <%= event.activity %>
                        </div>
                      </div>
                    </div>
                  <% end -%>
                </td>
                <td class="px-6 py-4">
                  <div class="text-sm text-gray-200"><%= event.event_details %></div>
                </td>
                <td class="px-6 py-4 whitespace-nowrap">
                  <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                    Active
                  </span>
                </td>
                <td class="px-5 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <a href="<%= edit_event_path(event) %>" class="text-blue-400 hover:text-indigo-200 mr-4">Edit</a>
                  <%# button_to "Borrar", destroy_event_path, method: :delete, data: { turbo: false },
                      class: "text-blue-400 hover:text-indigo-200"%>
                  <%= link_to "Delete", event_path(event), method: :delete, class: "text-blue-400 hover:text-indigo-200", data: {confirm: "seguro?"} %>
                </td>
              </tr>
            <% end -%>

            <!-- More people... -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

</section>

app/views/events/new.html.erb
<!-- Required form plugin -->
<link
  href="https://cdn.jsdelivr.net/npm/@tailwindcss/custom-forms@0.2.1/dist/custom-forms.css"
  rel="stylesheet"
/>
<section class="px-4 md:px-10 overflow-auto custom-scrollbar text-white" style="z-index: 999;">
  <%= render 'form' %>
</section>

app/views/events/show.html.erb
<div class="shadow-md rounded-md overflow-hidden text-center px-[100px] z-20  mx-auto">
  <div class="py-3 px-5 bg-black text-gray-200"><%= @event.activity %></div>
  <div class="p-5 bg-gray-900 text-gray-100 ">
    <h5 class="text-xl font-semibold mb-2"><%= @event.name %></h5>
    <p class="mb-4">
      <%= @event.event_details %>
    </p>

    <a class="bg-purple-500 text-white hover:bg-purple-700 active:bg-purple-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
      href="/events" type="button">
      volver
    </a>
    <%= link_to "Editar", edit_event_path(@event), class: "bg-purple-500 hover:bg-purple-700 text-white active:bg-purple-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" %>

    <% if @event.published_at.present? %>
      <div class="flex flex-col my-4 items-center">
        <div class="w-full flex flex-col">
          <%= link_to "Actualizar mensaje en todos los servidores", event_republish_path(@event), class: "bg-purple-500 text-white active:bg-purple-600 hover:bg-purple-700 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150", data: { turbo:false, confirm: "Seguro? Este eveno ya ha sido publicado anteriormente."}  %>
          <hr class="mb-2 mt-2 border-gray-700">
          <% DiscordSetup.all.each do |setup| %>
            <%= link_to "Publicar de nuevo en Server: #{setup.server_name}, Canal: #{setup.channel_name}",
                event_publish_path(event_id: @event, setup_id: setup.id),
                class: "bg-purple-500 hover:bg-purple-700 text-white active:bg-purple-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
            %>
          <% end -%>
        </div>
        <span class="text-xs font-bold text-gray-500 mt-2">"Publicar de nuevo" manda un mensaje nuevo, no actualiza el ya mandado.</span>
        <span class="text-xs font-bold text-gray-500 mt-2">Este evento se publico en discord el <%= @event.published_at %></span>
      </div>
    <% else %>
      <%= link_to "Publicar en todos los discord", event_publish_path(@event), class: "bg-purple-500 text-white active:bg-purple-600 hover:bg-purple-700 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"  %>
      <% DiscordSetup.all.each do |setup| %>
        <%= link_to "Publicar en Server: #{setup.server_name}, Canal: #{setup.channel_name}",
            event_publish_path(event_id: @event, setup_id: setup.id),
            class: "bg-purple-500 hover:bg-purple-700 text-white active:bg-purple-600 font-bold uppercase text-xs px-4 py-2 rounded shadow hover:shadow-md outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150"
        %>
      <% end -%>
    <% end -%>

    <div class="flex w-full justify-center gap-4">
      <div class="flex-grow max-w-[50%]">
        <span class="font-bold text-xl text-gray-200">Confirmados</span>
        <ul class="mt-4">
          <% @event.event_attendees.coming.each do |attendee| %>
            <li class="font-bold"><%= attendee.role_icon.html_safe %> - <%= attendee.nickname || attendee.name %> - Guild: <%= attendee.guild %></li>
          <% end -%>
        </ul>
      </div>
      <% if @event.event_attendees.not_coming.any? %>
        <div class="flex-grow max-w-[50%]">
          <span class="font-bold text-xl text-gray-200">No Asistiran</span>
          <ul class="mt-4">
            <% @event.event_attendees.not_coming.each do |attendee| %>
              <li class="font-bold"><%= attendee.role_icon.html_safe %> - <%= attendee.nickname || attendee.name %> - Guild: <%= attendee.guild %></li>
            <% end -%>
          </ul>
        </div>
      <% end -%>
    </div>

  </div>
</div>
<!-- Card -->